pipeline {
    
        }
    
        environment {
        HOME = '.'


        } 
    } 
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
           }
        }
    
    }
}
