pipeline {
    agent {
        docker {
            //image 'node:lts-bullseye-slim' 
            image 'node:19-alpine'
            args '-p 3000:3000' 
        }
    
        environment {
        HOME = '.'


        } 
    } 
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
           }
        }
    
    }
}
